"""add revogado to sessoes

Revision ID: 0f17e6513b46
Revises: 001
Create Date: 2026-03-19 14:46:19.746186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f17e6513b46'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agendamentos_maquina'), table_name='agendamentos_checklist')
    op.drop_index(op.f('idx_agendamentos_vencimento'), table_name='agendamentos_checklist')
    op.create_index(op.f('ix_agendamentos_checklist_data_vencimento'), 'agendamentos_checklist', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_agendamentos_checklist_id'), 'agendamentos_checklist', ['id'], unique=False)
    op.create_unique_constraint('uq_agendamento_maquina_data', 'agendamentos_checklist', ['maquina_id', 'data_vencimento'])
    op.drop_index(op.f('idx_itens_agendamento'), table_name='itens_checklist')
    op.create_index(op.f('ix_itens_checklist_id'), 'itens_checklist', ['id'], unique=False)
    op.drop_index(op.f('idx_manuais_maquina'), table_name='manuais')
    op.create_index(op.f('ix_manuais_id'), 'manuais', ['id'], unique=False)
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    op.drop_index(op.f('idx_modelos_maquina'), table_name='modelos_checklist')
    op.create_index(op.f('ix_modelos_checklist_id'), 'modelos_checklist', ['id'], unique=False)
    op.drop_index(op.f('idx_os_maquina'), table_name='ordens_servico')
    op.drop_index(op.f('idx_os_operador'), table_name='ordens_servico')
    op.drop_index(op.f('idx_os_status'), table_name='ordens_servico')
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.add_column('sessoes', sa.Column('revogado', sa.Boolean(), server_default='false', nullable=True))
    op.drop_index(op.f('idx_sessoes_token'), table_name='sessoes')
    op.drop_index(op.f('idx_sessoes_usuario'), table_name='sessoes')
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    op.create_unique_constraint('uq_usuario_dispositivo', 'sessoes', ['usuario_id', 'dispositivo_id'])
    op.drop_index(op.f('idx_usuarios_apelido'), table_name='usuarios')
    op.drop_index(op.f('idx_usuarios_funcao'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.create_index(op.f('idx_usuarios_funcao'), 'usuarios', ['funcao'], unique=False)
    op.create_index(op.f('idx_usuarios_apelido'), 'usuarios', ['apelido'], unique=False)
    op.drop_constraint('uq_usuario_dispositivo', 'sessoes', type_='unique')
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.create_index(op.f('idx_sessoes_usuario'), 'sessoes', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_sessoes_token'), 'sessoes', ['token'], unique=False)
    op.drop_column('sessoes', 'revogado')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.create_index(op.f('idx_os_status'), 'ordens_servico', ['status'], unique=False)
    op.create_index(op.f('idx_os_operador'), 'ordens_servico', ['operador_id'], unique=False)
    op.create_index(op.f('idx_os_maquina'), 'ordens_servico', ['maquina_id'], unique=False)
    op.drop_index(op.f('ix_modelos_checklist_id'), table_name='modelos_checklist')
    op.create_index(op.f('idx_modelos_maquina'), 'modelos_checklist', ['maquina_id'], unique=False)
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_index(op.f('ix_manuais_id'), table_name='manuais')
    op.create_index(op.f('idx_manuais_maquina'), 'manuais', ['maquina_id'], unique=False)
    op.drop_index(op.f('ix_itens_checklist_id'), table_name='itens_checklist')
    op.create_index(op.f('idx_itens_agendamento'), 'itens_checklist', ['agendamento_id'], unique=False)
    op.drop_constraint('uq_agendamento_maquina_data', 'agendamentos_checklist', type_='unique')
    op.drop_index(op.f('ix_agendamentos_checklist_id'), table_name='agendamentos_checklist')
    op.drop_index(op.f('ix_agendamentos_checklist_data_vencimento'), table_name='agendamentos_checklist')
    op.create_index(op.f('idx_agendamentos_vencimento'), 'agendamentos_checklist', ['data_vencimento'], unique=False)
    op.create_index(op.f('idx_agendamentos_maquina'), 'agendamentos_checklist', ['maquina_id'], unique=False)
    # ### end Alembic commands ###